<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>EnginePseudo3D.FpsLib</PackageId>
    <Title>EnginePseudo3D.FpsLib</Title>
    <Product>EnginePseudo3D</Product>
    <Version>1.6.0</Version>
    <Authors>Speyd</Authors>
    <Company>Speyd</Company>
    <Copyright>Speyd</Copyright>
    <PackageIcon>iconNuGet.png</PackageIcon>
    <Description>This is a library for calculating and displaying the number of fps.</Description>
    <RepositoryUrl>https://github.com/Speyd/Game2_5D/tree/Version_3_0/FpsLib</RepositoryUrl>
    <PackageReadmeFile>README_FpsLib.md</PackageReadmeFile>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="C:\Users\Admin\Desktop\README_FpsLib.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="C:\Users\Admin\Downloads\iconNuGet.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SFML.System" Version="2.6.1" />
  </ItemGroup>

</Project>
