<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SFML.Net" Version="2.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataPipes\DataPipes.csproj" />
    <ProjectReference Include="..\EntityLib\EntityLib.csproj" />
    <ProjectReference Include="..\ScreenLib\ScreenLib.csproj" />
    <ProjectReference Include="..\TextureLib\TextureLib.csproj" />
  </ItemGroup>

</Project>
