<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>EnginePseudo3D.ProtoRender</PackageId>
    <Title>EnginePseudo3D.ProtoRender</Title>
    <Product>EnginePseudo3D</Product>
    <Version>2.3.0</Version>
    <Authors>Speyd</Authors>
    <Company>Speyd</Company>
    <Copyright>Speyd</Copyright>
    <Description>This is a library for using interfaces related to rendering.</Description>
    <PackageIcon>iconNuGet.png</PackageIcon>
    <RepositoryUrl>https://github.com/Speyd/Game2_5D/tree/Version_3_0/ProtoRender</RepositoryUrl>
    <PackageReadmeFile>README_ProtoRender.md</PackageReadmeFile>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="C:\Users\Admin\Desktop\README_ProtoRender.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="C:\Users\Admin\Downloads\iconNuGet.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="EnginePseudo3D.ControlLib" Version="1.8.9" />
	<PackageReference Include="EnginePseudo3D.HitBoxLib" Version="1.6.6" />
	<PackageReference Include="EnginePseudo3D.TextureLib" Version="1.6.2" />
	  
  </ItemGroup>

</Project>
