<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <PackageLicenseExpression>MIT OR Apache-2.0</PackageLicenseExpression>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>EnginePseudo3D.Core</PackageId>
    <Title>EnginePseudo3D</Title>
    <Product>EnginePseudo3D</Product>
    <Version>1.8.2</Version>
    <Authors>Speyd</Authors>
    <Company>Speyd</Company>
    <Description>This is an engine that uses raycasting method and SFML framework to render the scene. This project implements most of the mechanics for writing the game. Designed for quick setup and easy integration into your code!</Description>
    <PackageProjectUrl></PackageProjectUrl>
    <RepositoryUrl>https://github.com/Speyd/Game2_5D/tree/Version_3_0</RepositoryUrl>
    <PackageIcon>iconNuGet.png</PackageIcon>
    <PackageReadmeFile>README_Engine.md</PackageReadmeFile>
    <Copyright>Speyd</Copyright>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="C:\Users\Admin\Desktop\README_Engine.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="C:\Users\Admin\Downloads\iconNuGet.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="EnginePseudo3D.AnimationLib" Version="1.1.9" />
	  <PackageReference Include="EnginePseudo3D.ControlLib" Version="1.6.4" />
	  <PackageReference Include="EnginePseudo3D.DataPipes" Version="1.0.3" />
	  <PackageReference Include="EnginePseudo3D.DrawLib" Version="1.6.1" />
	  <PackageReference Include="EnginePseudo3D.EffectLib" Version="1.0.4" />
	  <PackageReference Include="EnginePseudo3D.FpsLib" Version="1.4.1" />
	  <PackageReference Include="EnginePseudo3D.HitBoxLib" Version="1.3.1" />
	  <PackageReference Include="EnginePseudo3D.MiniMapLib" Version="1.5.2" />
	  <PackageReference Include="EnginePseudo3D.MoveLib" Version="1.6.4" />
	  <PackageReference Include="EnginePseudo3D.ObstacleLib" Version="1.7.4" />
	  <PackageReference Include="EnginePseudo3D.PartsWorldLib" Version="1.4.4" />
	  <PackageReference Include="EnginePseudo3D.ProtoRender" Version="1.6.0" />
	  <PackageReference Include="EnginePseudo3D.RayTracingLib" Version="1.6.8" />
	  <PackageReference Include="EnginePseudo3D.RenderLib" Version="1.5.2" />
	  <PackageReference Include="EnginePseudo3D.ScreenLib" Version="1.0.3" />
	  <PackageReference Include="EnginePseudo3D.TextureLib" Version="1.1.2" />
	  <PackageReference Include="SixLabors.ImageSharp" Version="3.1.8" />  
  </ItemGroup>

</Project>
