<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EntityLib\EntityLib.csproj" />
    <ProjectReference Include="..\MapLib\MapLib.csproj" />
    <ProjectReference Include="..\MiniMapLib\MiniMapLib.csproj" />
    <ProjectReference Include="..\MoveLib\MoveLib.csproj" />
    <ProjectReference Include="..\TextField\TextField.csproj" />
    <ProjectReference Include="..\TextureWallCollisionDetection\TextureWallCollisionDetection.csproj" />
  </ItemGroup>

</Project>
