<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>EnginePseudo3D.DrawLib</PackageId>
    <Title>EnginePseudo3D.DrawLib</Title>
    <Product>EnginePseudo3D</Product>
    <Version>2.1.2</Version>
    <Authors>Speyd</Authors>
    <Company>Speyd</Company>
    <Copyright>Speyd</Copyright>
    <Description>This is a library for drawing objects on a texture.</Description>
    <PackageIcon>iconNuGet.png</PackageIcon>
    <PackageReadmeFile>README_DrawLib.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/Speyd/Game2_5D/tree/Version_3_0/DrawLib</RepositoryUrl>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="C:\Users\Admin\Desktop\README_DrawLib.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="C:\Users\Admin\Downloads\iconNuGet.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="EnginePseudo3D.RayTracingLib" Version="2.2.9" />
  </ItemGroup>

</Project>
