<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>EnginePseudo3D.ScreenLib</PackageId>
    <Title>EnginePseudo3D.ScreenLib</Title>
    <Version>1.0.3</Version>
    <Authors>Speyd</Authors>
    <Company>Speyd</Company>
    <Product>EnginePseudo3D</Product>
    <Description>This is a library for using and creating a screen.</Description>
    <Copyright>Speyd</Copyright>
    <PackageIcon>iconNuGet.png</PackageIcon>
    <RepositoryUrl>https://github.com/Speyd/Game2_5D/tree/Version_3_0/ScreenLib</RepositoryUrl>
    <PackageReadmeFile>README_ScreenLib.md</PackageReadmeFile>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="C:\Users\Admin\Desktop\README_ScreenLib.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="C:\Users\Admin\Downloads\iconNuGet.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NGenerics" Version="1.5.3" />
    <PackageReference Include="SFML.Net" Version="2.6.1" />
  </ItemGroup>

</Project>
