<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <None Include="RenderInterface\ISelfRenderable.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EntityLib\EntityLib.csproj" />
    <ProjectReference Include="..\ScreenLib\ScreenLib.csproj" />
    <ProjectReference Include="..\TextureLib\TextureLib.csproj" />
  </ItemGroup>

</Project>
