<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>EnginePseudo3D.RayTracingLib</PackageId>
    <Title>EnginePseudo3D.RayTracingLib</Title>
    <Product>EnginePseudo3D</Product>
    <Version>1.6.8</Version>
    <Authors>Speyd</Authors>
    <Company>Speyd</Company>
    <Copyright>Speyd</Copyright>
    <PackageIcon>iconNuGet.png</PackageIcon>
    <Description>This is a library for detecting when a ray hits an object and determining the coordinates of the hit on a texture.</Description>
    <RepositoryUrl>https://github.com/Speyd/Game2_5D/tree/Version_3_0/RayTracingLib</RepositoryUrl>
    <PackageReadmeFile>README_RayTracingLib.md</PackageReadmeFile>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="C:\Users\Admin\Desktop\README_RayTracingLib.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="C:\Users\Admin\Downloads\iconNuGet.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="EnginePseudo3D.ProtoRender" Version="1.6.0" />
  </ItemGroup>

</Project>
