<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>EnginePseudo3D.PartsWorldLib</PackageId>
    <Title>EnginePseudo3D.PartsWorldLib</Title>
    <Product>EnginePseudo3D</Product>
    <Version>1.4.4</Version>
    <Authors>Speyd</Authors>
    <Company>Speyd</Company>
    <Copyright>Speyd</Copyright>
    <Description>This is a library for creating and re-creating world parts (floor, etc.)</Description>
    <PackageIcon>iconNuGet.png</PackageIcon>
    <RepositoryUrl>https://github.com/Speyd/Game2_5D/tree/Version_3_0/PartsWorldLib</RepositoryUrl>
    <PackageReadmeFile>README_PartsWorldLib.md</PackageReadmeFile>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>	  
  </PropertyGroup>

  <ItemGroup>
    <None Include="C:\Users\Admin\Desktop\README_PartsWorldLib.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="C:\Users\Admin\Downloads\iconNuGet.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="EnginePseudo3D.EffectLib" Version="1.0.4" />
	<PackageReference Include="EnginePseudo3D.ProtoRender" Version="1.6.0" />
	<PackageReference Include="EnginePseudo3D.TextureLib" Version="1.1.2" />
  </ItemGroup>

</Project>
