<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnimationLib\AnimationLib.csproj" />
    <ProjectReference Include="..\EffectLib\EffectLib.csproj" />
    <ProjectReference Include="..\EntityLib\EntityLib.csproj" />
    <ProjectReference Include="..\HitBoxLib\HitBoxLib.csproj" />
    <ProjectReference Include="..\RayTracingLib\RayTracingLib.csproj" />
    <ProjectReference Include="..\Render\Render.csproj" />
    <ProjectReference Include="..\ScreenLib\ScreenLib.csproj" />
  </ItemGroup>

</Project>
